engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
      - 'vendor/'
      - 'spec/'
      - 'db/'
    config:
      languages:
      - ruby
      - javascript
  rubocop:
    enabled: true
    channel: rubocop-0-74
